# Generated by Django 3.0.3 on 2020-06-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermessage', '0002_auto_20200616_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='MessageText',
        ),
    ]
